# Limit pull request from develop branch only.
name: "Allowed Pull Request"

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Echo 
        env:
          BASE_REF: ${{ github.base_ref }}
          HEAD_REF: ${{ github.head_ref }}
        run: echo Merging $HEAD_REF into $BASE_REF