# Limit pull request from develop branch only.
name: "Allowed Pull Request"

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    env:
      BASE_REF: ${{ github.base_ref }}
      HEAD_REF: ${{ github.head_ref }}
    steps:
      - name: Echo 
        run: echo Merging $HEAD_REF into $BASE_REF
      - name: Compare
        if: ${{ github.head_ref == "develop" }}  
        run: echo Passing $HEAD_REF