# Limit pull request from develop branch only.
#
# https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
# https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context
# https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables
#
name: "Allowed Pull Request"

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    env:
      BASE_REF: ${{ github.base_ref }}
      HEAD_REF: ${{ github.head_ref }}
    steps:
      - id: compare
        if: ${{ github.head_ref }} == 'develop' 
        run: echo Passing ${{ github.head_ref }}
      - id: display
        run: echo exit code ${{ steps.compare.exitcode }}