# Limit pull request from develop branch only.
name: "Allowed Pull Request"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Echo 
        env:
          BRANCH: ${{ github.payload.pull_request.head.ref }}
        run: echo Branch is [ $BRANCH ]